name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build your Docker image
      - name: Build Docker Image
        run: |
          docker build -t basharahmed/flask-app:latest .

      # Log in to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Push the Docker image to DockerHub
      - name: Push Docker Image to DockerHub
        run: docker push basharahmed/flask-app:latest

      # SSH into your EC2 instance and deploy the updated container
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Logging into DockerHub on EC2..."
            sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
            
            echo "Pulling the latest Docker image..."
            sudo docker pull basharahmed/flask-app:latest
            
            echo "Checking for an existing container..."
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^flask-container\$"; then
              echo "Stopping and removing existing flask-container..."
              sudo docker stop flask-container
              sudo docker rm flask-container
            else
              echo "No existing container found."
            fi
            
            echo "Cleaning up unused Docker resources..."
            sudo docker system prune -f
            
            echo "Deploying the updated container with both Flask and NGINX..."
            sudo docker run -d --name flask-container -p 80:80 basharahmed/flask-app:latest
